# Generated by Django 5.0.4 on 2024-05-26 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nivelesactividadfisica',
            old_name='descripcion',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='perfilembarazo',
            old_name='altura_mc',
            new_name='altura_cm',
        ),
    ]
