# Generated by Django 5.0.4 on 2024-04-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilembarazo',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfilembarazo',
            name='fecha_ultima_menstruacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfilembarazo',
            name='sintomas',
            field=models.ManyToManyField(blank=True, to='webapp.sintoma'),
        ),
    ]
