# Generated by Django 5.0.4 on 2024-05-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_perfilembarazo_edad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoEmbarazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.IntegerField(verbose_name='Número de Semana')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='infoembarazo/', verbose_name='Imagen')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
            ],
        ),
    ]
